import { create } from 'zustand';

export type Locale = 'id' | 'en';

interface LanguageState {
    locale: Locale;
    setLocale: (locale: Locale) => void;
}

export const useLanguageStore = create<LanguageState>((set) => ({
    locale:
        (typeof window !== 'undefined'
            ? (localStorage.getItem('locale') as Locale)
            : 'id') || 'id',
    setLocale: (locale) => {
        if (typeof window !== 'undefined') {
            localStorage.setItem('locale', locale);
        }
        set({ locale });
    },
}));

export const dictionary: Record<Locale, Record<string, string>> = {
    id: {
        // Sidebar Category
        'MANAGEMENT': 'MANAJEMEN',
        'EMPLOYEE': 'KEPEGAWAIAN',
        'CORRESPONDENCE': 'PERSURATAN',
        'DATA': 'DATA PERSURATAN',
        'Dashboard': 'Beranda',
        'Configuration': 'Konfigurasi',
        'Referencies': 'Referensi',
        'Master': 'Data Master',
        'Employees': 'Pegawai',
        'Attendances': 'Kehadiran',
        'Rekapitulasi': 'Rekapitulasi',
        'Riwayat Claim': 'Riwayat Klaim',
        'Riwayat Export': 'Riwayat Export',
        'Events': 'Kegiatan / Acara',
        'Users': 'Pengguna',
        'Roles': 'Peran',
        'Permission': 'Izin Akses',
        'Access Role': 'Hak Akses Peran',
        'Access User': 'Hak Akses Pengguna',
        'Correspondence': 'Persuratan',
        'ACADEMIC': 'AKADEMIK',
        'Class Schedules': 'Jadwal Kelas',
        'Classrooms': 'Ruang Kelas',
        'Attendances Recap': 'Rekap Kehadiran',
        'Rekap Departemen': 'Rekap Departemen',
        'UTILITY': 'UTILITAS',
        'Whiteboard': 'Papan Tulis (Whiteboard)',

        // Menus
        'Time Off Requests': 'Permohonan Izin',
        'Circular Letters': 'Surat Edaran',
        'Assignment Letters': 'Surat Tugas',
        'SK / Decrees': 'Surat Keputusan (SK)',
        'Statement Letters': 'Surat Keterangan',
        'Recommendation Letters': 'Surat Rekomendasi',
        'My Leaves': 'Cuti Saya',
        'Leave Requests': 'Permohonan Cuti',
        'Shifts': 'Data Shift',
        'Shift Kerja': 'Shift Kerja',
        'Schedules': 'Jadwal',
        'Swap Requests': 'Tukar Shift',
        'Menu': 'Menu',
        'Departments': 'Departemen',
        'Positions': 'Jabatan',
        'Locations': 'Lokasi',
        'Holidays': 'Hari Libur',

        // Actions
        'Action': 'Pilihan',
        'Approve': 'Setujui',
        'Reject': 'Tolak',
        'Detail': 'Rincian',
        'Delete': 'Hapus',
        'Edit': 'Ubah',
        'View': 'Lihat',
        'Read Letter': 'Baca Surat',
        'Add Letter': 'Tambah Surat',
        'Add Decree': 'Tambah SK',
        'Create New Decree (SK)': 'Buat Surat Keputusan (SK) Baru',
        'Edit Decree (SK)': 'Ubah Surat Keputusan (SK)',
        'Issue Recommendation': 'Terbitkan Rekomendasi',
        'Request Letter': 'Ajukan Permohonan',
        'Cancel': 'Batal',
        'Submit': 'Kirim',
        'Submit Request': 'Ajukan Permohonan',
        'Back': 'Kembali',
        'Download PDF': 'Unduh PDF',
        'Open in New Tab': 'Buka di Tab Baru',
        'Upload PDF Document': 'Unggah Dokumen PDF',
        'Choose PDF File': 'Pilih Berkas PDF',
        'Approve & Upload': 'Setujui & Unggah',
        'Reject Request': 'Tolak Permohonan',
        'Issue & Upload': 'Terbitkan & Unggah',
        'Send & Issue': 'Kirim & Terbitkan',
        'Update Decree': 'Perbarui SK',
        'Apply Leave': 'Ajukan Cuti',

        // Titles and Subtitles
        'official_decree_sk': 'Surat Keputusan Resmi (SK)',
        'review_pending_statement':
            'Tinjau permohonan surat keterangan, setujui dengan mengunggah PDF, atau tolak permohonan.',
        'request_active_employment':
            'Ajukan surat keterangan aktif bekerja, rincian gaji, aktif kuliah, atau sertifikat SKPI.',
        'review_pending_recommendation':
            'Tinjau dan terbitkan surat rekomendasi resmi langsung untuk pegawai.',
        'official_recommendation_umsu':
            'Daftar Surat Rekomendasi resmi Universitas Muhammadiyah Sumatera Utara.',
        'issue_and_manage_decrees':
            'Terbitkan dan kelola Surat Keputusan (SK) resmi bagi pegawai yang dituju.',
        'official_decrees_issued':
            'Daftar Surat Keputusan (SK) resmi yang diterbitkan untuk Anda.',
        'manage_circular_letters':
            'Kelola dan distribusikan surat edaran resmi ke departemen/bagian secara online.',
        'official_circular_letters_umsu':
            'Daftar Surat Edaran resmi Universitas Muhammadiyah Sumatera Utara.',
        'Apply for and track your time-off requests':
            'Ajukan dan pantau permohonan waktu istirahat Anda.',
        'Manage employee leave and time-off requests':
            'Kelola permohonan cuti dan waktu istirahat pegawai.',

        // Dashboard
        'Monthly Attendance': 'Presensi Bulanan',
        'Overall Attendance': 'Presensi Keseluruhan',

        // Labels
        'Position': 'Jabatan',
        'Department': 'Departemen',
        'Not set': 'Belum di-set',
        'Unknown': 'Tidak diketahui',
        'active': 'Aktif',
        'non_active': 'Non-Aktif',
        'permanent': 'Tetap',
        'contract': 'Kontrak',
        'honorarium': 'Honorarium',
        'internship': 'Magang',
        'Applicant': 'Pemohon',
        'Recipient': 'Penerima',
        'Recipient Employee': 'Pegawai Penerima',
        'Recipient Employee / User': 'Pegawai / Pengguna Penerima',
        'Letter Type': 'Jenis Surat',
        'Reason': 'Alasan / Tujuan',
        'Reason / Purpose of Request': 'Alasan / Tujuan Permohonan',
        'Reason / Purpose / Notes': 'Alasan / Tujuan / Catatan Tambahan',
        'Purpose / Notes': 'Tujuan / Catatan',
        'Status': 'Status',
        'Result / Reference': 'Hasil / Referensi',
        'Actions': 'Aksi',
        'Search': 'Cari...',
        'Pending': 'MENUNGGU',
        'Approved': 'DISETUJUI',
        'Rejected': 'DITOLAK',
        'Search letter number or title...': 'Cari nomor surat atau judul...',
        'Search by number, reason, or applicant...':
            'Cari nomor, alasan, atau nama pemohon...',
        'Search by number, notes, or employee...':
            'Cari nomor, catatan, atau nama pegawai...',
        'All Status': 'Semua Status',
        'No data found.': 'Data tidak ditemukan.',
        'No statement letters found.': 'Surat keterangan tidak ditemukan.',
        'No recommendation letters found.':
            'Surat rekomendasi tidak ditemukan.',
        'No SK / Decrees found.': 'Surat Keputusan (SK) tidak ditemukan.',
        'No circular letters found.': 'Surat edaran tidak ditemukan.',
        'Letter Number': 'Nomor Surat',
        'SK Number': 'Nomor SK',
        'Letter Date': 'Tanggal Surat',
        'Decree Date': 'Tanggal SK',
        'Decree Title': 'Judul SK',
        'Decree (SK) Title': 'Judul Surat Keputusan (SK)',
        'Decree (SK) Number': 'Nomor Surat Keputusan (SK)',
        'Signed By': 'Ditandatangani Oleh',
        'Signature Type': 'Tipe Tanda Tangan',
        'Wet Signature': 'Tanda Tangan Basah',
        'Digital Signature (TTE)': 'Tanda Tangan Digital (TTE)',
        'Digital TTE': 'Digital (TTE)',
        'Digital (TTE)': 'Digital (TTE)',
        'Targeted Employees': 'Pegawai yang Dituju',
        'Targets': 'Target Penerima',
        'Document Information': 'Informasi Dokumen',
        'Document Details': 'Rincian Dokumen',
        'Integrated PDF Canvas': 'Peninjau PDF Terintegrasi',
        'Recommendation Issued': 'Rekomendasi Diterbitkan',
        'Letter Information': 'Informasi Surat',
        'Request Details': 'Rincian Permohonan',
        'Issued Date': 'Tanggal Terbit',
        'Date': 'Tanggal',
        'Title of Decree': 'Judul Surat Keputusan (SK)',
        'Title of Circular Letter': 'Judul Surat Edaran',
        'Title of Letter': 'Judul Surat',
        'Summary Description': 'Ringkasan Deskripsi',
        'Recipients': 'Penerima',
        'Shift Management': 'Manajemen Shift',
        'Shift Schedules': 'Jadwal Shift',
        'Kelola data master shift kerja.': 'Kelola data master shift kerja.',
        'Atur jadwal shift dan tukar shift.':
            'Atur jadwal shift dan tukar shift.',
        'Kelola pengajuan tukar shift antar pegawai.':
            'Kelola pengajuan tukar shift antar pegawai.',
        'Hanya akun yang terhubung ke data pegawai yang dapat mengajukan tukar.':
            'Hanya akun yang terhubung ke data pegawai yang dapat mengajukan tukar.',
        'Ajukan Tukar Shift': 'Ajukan Tukar Shift',
        'Atur Shift': 'Atur Shift',
        'Belum ada pengajuan tukar shift.': 'Belum ada pengajuan tukar shift.',
        'Holiday Management': 'Manajemen Hari Libur',
        'Manage list of holidays.': 'Kelola daftar hari libur.',
        'Add Holiday': 'Tambah Hari Libur',
        'Search holiday...': 'Cari hari libur...',
        'Holiday Name': 'Nama Hari Libur',
        'No holidays found.': 'Tidak ada hari libur ditemukan.',
        'Edit Holiday': 'Ubah Hari Libur',
        'Delete Holiday': 'Hapus Hari Libur',
        'Change the details of this holiday.': 'Ubah detail hari libur ini.',
        'Add a new holiday to the system.':
            'Tambahkan data hari libur baru ke dalam sistem.',
        'Enter holiday name': 'Masukkan nama hari libur',
        'Active': 'Aktif',
        'Inactive': 'Tidak Aktif',
        'Kelola hierarki menu navigasi sistem.':
            'Kelola hierarki menu navigasi sistem.',
        'Issue and assign official letters of duties to specific employees.':
            'Terbitkan dan berikan surat tugas resmi kepada pegawai tertentu.',
        'Official assignment letters of duties issued to you.':
            'Daftar surat tugas resmi yang diterbitkan untuk Anda.',
        'Select all': 'Pilih Semua',
        'Save': 'Simpan',
        'Update': 'Perbarui',
        'Confirm': 'Konfirmasi',
        'Settings': 'Pengaturan',
        'Log out': 'Keluar',
        'Language / Bahasa': 'Bahasa',
        'Total Days': 'Total Hari',
        'Attachment': 'Lampiran',
        'Leave Balance Information': 'Informasi Sisa Cuti',
        'Total Quota': 'Total Jatah',
        'Used / Pending': 'Terpakai / Tertunda',
        'Remaining': 'Sisa',
        'Days': 'Hari',
        'Start Date': 'Tanggal Mulai',
        'End Date': 'Tanggal Selesai',
        'to': 's/d',
        'Required for some leaves': 'Wajib untuk beberapa jenis cuti',
        'Choose File': 'Pilih Berkas',
        'PDF, JPG, PNG format, max 2MB': 'Format PDF, JPG, PNG, maks 2MB',
        '*The remaining balance above applies to the current year. Ensure you do not apply for more than your remaining days.':
            '*Sisa cuti di atas berlaku untuk tahun berjalan. Pastikan Anda tidak mengajukan lebih dari sisa cuti Anda.',
        'Employee': 'Pegawai',
        'Leave Details': 'Rincian Cuti',
        'Leave Request Details': 'Rincian Permohonan Cuti',

        // Modals
        'Create Time Off Request': 'Buat Permohonan Izin',
        'Submit a time off request for an employee.': 'Ajukan permohonan izin untuk pegawai.',
        'Employee Email': 'Email Pegawai',
        'Select Employee': 'Pilih Pegawai',
        'Leave Type': 'Jenis Cuti',
        'Casual Leave': 'Izin Biasa',
        'Sick Leave': 'Izin Sakit',
        'Annual Leave': 'Cuti Tahunan',
        'Unpaid Leave': 'Cuti di Luar Tanggungan',
        'Reason (Optional)': 'Alasan (Opsional)',
        'Create & Approve': 'Buat & Setujui',
        'Create Request': 'Buat Permohonan',
        'Provide reason for time off...': 'Berikan alasan permohonan izin...',
        'Approve Time Off Request': 'Setujui Permohonan Izin',
        'Reject Time Off Request': 'Tolak Permohonan Izin',
        'Time Off Request Details': 'Rincian Permohonan Izin',
        'Delete Statement Letter': 'Hapus Surat Keterangan',
        'Delete Recommendation Letter': 'Hapus Surat Rekomendasi',
        'Delete SK / Decree': 'Hapus Surat Keputusan (SK)',
        'Delete Circular Letter': 'Hapus Surat Edaran',
        'confirm_delete_statement':
            'Apakah Anda yakin ingin menghapus permohonan surat keterangan ini? Berkas PDF yang diunggah juga akan dihapus secara permanen.',
        'confirm_delete_recommendation':
            'Apakah Anda yakin ingin menghapus surat rekomendasi ini? Berkas PDF yang diunggah juga akan dihapus secara permanen.',
        'confirm_delete_sk':
            'Apakah Anda yakin ingin menghapus Surat Keputusan (SK) ini? Berkas PDF yang diunggah juga akan dihapus secara permanen dari server.',
        'confirm_delete_circular':
            'Apakah Anda yakin ingin menghapus surat edaran ini? Berkas PDF yang diunggah juga akan dihapus secara permanen dari server.',
        'Approve Letter Request': 'Setujui Permohonan Surat',
        'Reject Letter Request': 'Tolak Permohonan Surat',
        'Rejection Reason': 'Alasan Penolakan',
        'Write a brief explanation for rejecting this request...':
            'Tulis penjelasan singkat mengenai penolakan permohonan ini...',
        'Signer Authority': 'Pejabat Penandatangan',
        'Select Signer': 'Pilih Penandatangan',
        'Select Recipient': 'Pilih Penerima',
        'Daftar Partisipan': 'Participant List',
        'Manage and view attendance records.':
            'Kelola dan lihat rekam data kehadiran.',
        'Rekapitulasi Absensi': 'Attendance Recapitulation',
        'Laporan ringkasan data absensi karyawan':
            'Summary report of employee attendance data.',
        'Manajemen hak akses role terhadap menu dan aksi sistem.':
            'Manage role access rights to menus and system actions.',
        'Manajemen hak akses user terhadap menu dan aksi sistem.':
            'Manage user access rights to menus and system actions.',
        'Menu Management': 'Manajemen Menu',
        'Permission Management': 'Manajemen Izin Akses',
        'Kelola permission sistem.': 'Manage system permissions.',
        'Role Management': 'Manajemen Peran',
        'Kelola role akses sistem.': 'Manage system access roles.',
        'User Management': 'Manajemen Pengguna',
        'Kelola data pengguna dan akses peran mereka.':
            'Manage user data and their role access.',
        'Fill out the form below to assign and distribute the official task letter.':
            'Isi formulir di bawah ini untuk memberikan dan mendistribusikan surat tugas resmi.',
        'Correspondence - Assignment Letters': 'Persuratan - Surat Tugas',
        'Fill out the form below to distribute the official circular letter.':
            'Isi formulir di bawah ini untuk mendistribusikan surat edaran resmi.',
        'Correspondence - Circular Letters': 'Persuratan - Surat Edaran',
        'Fill out the form below to issue and distribute the official decree (Surat Keputusan).':
            'Isi formulir di bawah ini untuk menerbitkan dan mendistribusikan surat keputusan (SK) resmi.',
        'Event Management': 'Manajemen Kegiatan',
        'Kelola jadwal event, rapat, dan agenda kantor secara online maupun offline.':
            'Manage event schedules, meetings, and office agendas online or offline.',
        'Employee Management': 'Manajemen Pegawai',
        'Kelola data pegawai dan informasi kepegawaian.':
            'Manage employee data and HR information.',
        'Department Management': 'Manajemen Departemen',
        'Kelola struktur organisasi dan departemen.':
            'Kelola struktur organisasi dan departemen.',
        'Location Management': 'Manajemen Lokasi',
        'Kelola data lokasi.': 'Kelola data lokasi.',
        'Position Management': 'Manajemen Jabatan',
        'Kelola jabatan/jenjang pegawai.': 'Kelola jabatan/jenjang pegawai.',
        'Create New Circular Letter': 'Buat Surat Edaran Baru',
        'Edit Circular Letter': 'Ubah Surat Edaran',
        'Create New Assignment Letter': 'Buat Surat Tugas Baru',
        'Edit Assignment Letter': 'Ubah Surat Tugas',
        'Employees by Work Unit': 'Karyawan menurut Unit Kerja',
        'Overview': 'Ringkasan',
        "Welcome back! Here's what's happening today.":
            'Selamat datang kembali! Berikut informasi untuk hari ini.',
        'Employees Total': 'Total Pegawai',
        'Registered in the system': 'Terdaftar di dalam sistem',
        'Active Events': 'Kegiatan Aktif',
        'Events that are currently running': 'Kegiatan yang sedang berlangsung',
        'Attendance (Today)': 'Kehadiran (Hari Ini)',
        'Employees present today': 'Pegawai yang hadir hari ini',
        'Total Department': 'Total Departemen',
        'Registered work unit': 'Unit kerja yang terdaftar',
        'Employee Attendance':
            'Kehadiran Pegawai',
        'There is no absence data.':
            'Tidak ada data kehadiran.',
        'There is no employee data yet.': 'Belum ada data pegawai.',
        'Complete Data': 'Data Lengkap',
        'Incomplete Data': 'Belum Mengisi',
        'Work units have been filled': 'Sudah mengisi unit kerja',
        'Work units not yet filled': 'Belum mengisi unit kerja',
        'Report summary of employee attendance data':
            'Laporan ringkasan data absensi karyawan',
        'Export Excel': 'Ekspor Excel',
        'Attendance Recapitulation': 'Rekapitulasi Absensi',
        'All Type': 'Semua Tipe',
        'Alfa': 'Alpa',
        'Late': 'Terlambat',

        // Dynamic Performance Rules
        'Sangat Baik': 'Sangat Baik',
        'Cukup': 'Cukup',
        'Perlu Evaluasi': 'Perlu Evaluasi',
        'SP 1': 'SP 1',
        'SP 2': 'SP 2',
        'SP 3': 'SP 3',
        'Terlambat': 'Terlambat',
        'Tepat Waktu': 'Tepat Waktu',
        'Alpa': 'Alpa',

        'Hijau': 'Hijau',
        'Oranye': 'Oranye',
        'Merah': 'Merah',
        'Biru': 'Biru',
        'Kuning': 'Kuning',
        'Abu-abu': 'Abu-abu',
        'Ungu': 'Ungu',

        'Reference Settings': 'Pengaturan Referensi',
        'Kelola konfigurasi sistem dan referensi.':
            'Kelola konfigurasi sistem dan referensi.',
        'Pengaturan Performa (Rentang Pelanggaran)':
            'Pengaturan Performa (Rentang Pelanggaran)',
        'Konfigurasi rentang akumulasi hari terlambat dan alpa untuk menentukan label performa secara dinamis.':
            'Konfigurasi rentang akumulasi hari terlambat dan alpa untuk menentukan label performa secara dinamis.',
        'Min': 'Min',
        'Max': 'Maks',
        'Label Teks': 'Label Teks',
        'Warna Label': 'Warna Label',
        'Tambah Rentang Baru': 'Tambah Rentang Baru',
        'Simpan Semua Pengaturan': 'Simpan Semua Pengaturan',
        'Tak Terhingga': 'Tak Terhingga',

        // Push Notifications
        'Push Notifications': 'Kelola Pemberitahuan',
        'Push notification berhasil dikirim.': 'Notifikasi berhasil dikirim.',
        'Gagal mengirim push notification. Pastikan input valid.': 'Gagal mengirim notifikasi. Pastikan input valid.',
        'Kirim dan kelola riwayat notifikasi langsung ke perangkat pegawai.': 'Kirim dan kelola riwayat notifikasi langsung ke perangkat pegawai.',
        'Kirim Notifikasi': 'Kirim Notifikasi',
        'Waktu': 'Waktu',
        'Judul': 'Judul',
        'Isi Pesan': 'Isi Pesan',
        'Penerima': 'Penerima',
        'Pengirim': 'Pengirim',
        'Pegawai': 'Pegawai',
        'Belum ada riwayat notifikasi.': 'Belum ada riwayat notifikasi.',
        'Kirim Notifikasi Baru': 'Kirim Notifikasi Baru',
        'Pilih pegawai secara spesifik untuk menerima notifikasi ini.': 'Pilih pegawai secara spesifik untuk menerima notifikasi ini.',
        'Batal': 'Batal',
        'Mengirim...': 'Mengirim...',
        'Judul Notifikasi': 'Judul Notifikasi',
        'Contoh: Pembaruan Biodata': 'Contoh: Pembaruan Biodata',
        'Pesan': 'Pesan',
        'Silakan lengkapi biodata Anda di menu profil...': 'Silakan lengkapi biodata Anda di menu profil...',
        'Kirim Ke (Pegawai)': 'Kirim Ke (Pegawai)',
        'Pilih satu atau lebih pegawai': 'Pilih satu atau lebih pegawai',

        // Settings
        'Profile information': 'Informasi Profil',
        'Update your name and email address': 'Perbarui informasi nama dan alamat email Anda.',
        'Update your profile information.': 'Perbarui informasi profil Anda.',
        'Email Address': 'Alamat Email',
        'Name': 'Nama',
        'Verification link has been sent to your email address': 'Link verifikasi telah dikirim ke alamat email Anda.',
        'Full name': 'Nama Lengkap',
        'Profile settings': 'Pengaturan Profil',
        'Your email address is unverified.': 'Alamat email Anda belum terverifikasi.',
        'Click here to resend the verification email.': 'Klik di sini untuk mengirim ulang email verifikasi.',
        'Update your profile information': 'Perbarui informasi profil Anda.',
        'Warning': 'Peringatan',
        'Please proceed with caution, this cannot be undone.': 'Harap lanjutkan dengan hati-hati, tindakan ini tidak dapat dibatalkan.',
        'Are you sure you want to delete your account?': 'Apakah Anda yakin ingin menghapus akun Anda?',
        'Once your account is deleted, all of its resources and data will also be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.': 'Setelah akun Anda dihapus, semua sumber daya dan datanya juga akan dihapus secara permanen. Harap masukkan kata sandi Anda untuk mengonfirmasi bahwa Anda ingin menghapus akun Anda secara permanen.',
        'Password': 'Kata Sandi',
        'Profile photo': 'Foto Profil',
        'Update your profile picture': 'Perbarui foto profil Anda.',
        'Change Photo': 'Ganti Foto',
        'Save Photo': 'Simpan Foto',
        
        // Lecturer Courses
        'Mata Kuliah Anda': 'Mata Kuliah Anda',
        'Kelola dan pantau seluruh mata kuliah yang Anda ampu pada periode akademik saat ini.': 'Kelola dan pantau seluruh mata kuliah yang Anda ampu pada periode akademik saat ini.',
        'Total Kelas': 'Total Kelas',
        'Sesuai Jadwal': 'Sesuai Jadwal',
        'Lihat Partisipan': 'Lihat Partisipan',
        'Belum Ada Mata Kuliah': 'Belum Ada Mata Kuliah',
        'Anda belum terdaftar sebagai pengajar untuk mata kuliah apapun pada periode ini.': 'Anda belum terdaftar sebagai pengajar untuk mata kuliah apapun pada periode ini.',
        'Sebelumnya': 'Sebelumnya',
        'Selanjutnya': 'Selanjutnya',
        'Halaman': 'Halaman',
        'dari': 'dari',
        'Academic Semester': 'Semester Akademik',
        'Partisipan Kelas': 'Partisipan Kelas',
        'Daftar Mahasiswa': 'Daftar Mahasiswa',
        'Total': 'Total',
        'mahasiswa terdaftar pada mata kuliah ini.': 'mahasiswa terdaftar pada mata kuliah ini.',
        'Gagal memuat data partisipan.': 'Gagal memuat data partisipan.',
        'Terjadi kesalahan saat memuat data partisipan.': 'Terjadi kesalahan saat memuat data partisipan.',
        'No': 'No',
        'NPM': 'NPM',
        'Nama Mahasiswa': 'Nama Mahasiswa',
        'Jenis Kelamin': 'Jenis Kelamin',
        'Program Studi': 'Program Studi',
        'Kelas': 'Kelas',
        'Laki-laki': 'Laki-laki',
        'Perempuan': 'Perempuan',
        'Belum ada mahasiswa yang terdaftar': 'Belum ada mahasiswa yang terdaftar',
        'Hal': 'Hal',
        'Academic': 'Akademik',
        'Courses': 'Mata Kuliah',
        'Teaching Schedules': 'Jadwal Mengajar',
        'Jadwal Mengajar': 'Jadwal Mengajar',
        'Jadwal Mengajar Anda': 'Jadwal Mengajar Anda',
        'Pantau jadwal mengajar Anda untuk periode akademik saat ini.': 'Pantau jadwal mengajar Anda untuk periode akademik saat ini.',
        'Total Jadwal': 'Total Jadwal',
        'Belum ada jadwal': 'Belum ada jadwal',
        'Belum Ada Jadwal': 'Belum Ada Jadwal',
        'Anda belum memiliki jadwal mengajar untuk periode ini.': 'Anda belum memiliki jadwal mengajar untuk periode ini.',

        // Attendance Claims
        'Riwayat Claim Absensi': 'Riwayat Klaim Absensi',
        'Daftar riwayat klaim absensi yang dilakukan oleh admin atau manajer.': 'Daftar riwayat klaim absensi yang dilakukan oleh admin atau manajer.',
        'Data Riwayat Claim': 'Data Riwayat Klaim',
        'Waktu Klaim': 'Waktu Klaim',
        'Pegawai (Email)': 'Pegawai (Email)',
        'Diklaim Oleh': 'Diklaim Oleh',
        'Alasan': 'Alasan',
        'Tidak ada riwayat klaim.': 'Tidak ada riwayat klaim.',
        'Failed to load data for claim': 'Gagal memuat data untuk klaim',
        'Attendances claim generation has been started in the background.': 'Pembuatan klaim kehadiran telah dimulai di latar belakang.',
        'Failed to process attendance claims.': 'Gagal memproses klaim kehadiran.',
        'Claim': 'Klaim',
        'Attendances Claim': 'Klaim Kehadiran',
        'Submit attendance claims for employees.': 'Ajukan klaim kehadiran untuk pegawai.',
        'Select Employees': 'Pilih Pegawai',
        'Date Range': 'Rentang Tanggal',
        'Include Check-In': 'Sertakan Check-In',
        'Check-In Time': 'Waktu Check-In',
        'Include Check-Out': 'Sertakan Check-Out',
        'Check-Out Time': 'Waktu Check-Out',
        'Location': 'Lokasi',
        'Select Location': 'Pilih Lokasi',
        'Catatan / Alasan Claim': 'Catatan / Alasan Klaim',
        'Masukkan alasan melakukan claim ini...': 'Masukkan alasan melakukan klaim ini...',
        'Saving...': 'Menyimpan...',
        'Submit Claim': 'Kirim Klaim',
        'Konfirmasi Data': 'Konfirmasi Data',
        'Pastikan data attendance claim yang Anda isi sudah benar. Anda yakin ingin melanjutkan?': 'Pastikan data klaim kehadiran yang Anda isi sudah benar. Anda yakin ingin melanjutkan?',
        'Ya, Simpan': 'Ya, Simpan',
        'Cari...': 'Cari...',
        'Cari': 'Cari',
    },

    en: {
        // Sidebar Category
        'MANAGEMENT': 'MANAGEMENT',
        'EMPLOYEE': 'EMPLOYEE',
        'CORRESPONDENCE': 'CORRESPONDENCE',
        'DATA': 'DATA PERSURATAN',
        'Dashboard': 'Dashboard',
        'Configuration': 'Configuration',
        'Referencies': 'Referencies',
        'Master': 'Master',
        'Employees': 'Employees',
        'Attendances': 'Attendances',
        'Rekapitulasi': 'Recapitulation',
        'Riwayat Claim': 'Claim History',
        'Riwayat Export': 'Export History',
        'Events': 'Events',
        'Users': 'Users',
        'Roles': 'Roles',
        'Permission': 'Permission',
        'Access Role': 'Access Role',
        'Access User': 'Access User',
        'Correspondence': 'Correspondence',
        'ACADEMIC': 'ACADEMIC',
        'Class Schedules': 'Class Schedules',
        'Classrooms': 'Classrooms',
        'Attendances Recap': 'Attendances Recap',
        'Rekap Departemen': 'Dept Recap',
        'UTILITY': 'UTILITY',
        'Whiteboard': 'Whiteboard',

        // Menus
        'Time Off Requests': 'Time Off Requests',
        'Circular Letters': 'Circular Letters',
        'Assignment Letters': 'Assignment Letters',
        'SK / Decrees': 'SK / Decrees',
        'Statement Letters': 'Statement Letters',
        'Recommendation Letters': 'Recommendation Letters',
        'My Leaves': 'My Leaves',
        'Leave Requests': 'Leave Requests',
        'Shifts': 'Shifts',
        'Shift Kerja': 'Work Shifts',
        'Schedules': 'Schedules',
        'Swap Requests': 'Swap Requests',
        'Menu': 'Menu',
        'Departments': 'Departments',
        'Positions': 'Positions',
        'Locations': 'Locations',
        'Holidays': 'Holidays',

        // Actions
        'Action': 'Action',
        'Approve': 'Approve',
        'Reject': 'Reject',
        'Detail': 'Detail',
        'Delete': 'Delete',
        'Edit': 'Edit',
        'View': 'View',
        'Read Letter': 'Read Letter',
        'Add Letter': 'Add Letter',
        'Add Decree': 'Add Decree (SK)',
        'Create New Decree (SK)': 'Create New Decree (SK)',
        'Edit Decree (SK)': 'Edit Decree (SK)',
        'Issue Recommendation': 'Issue Recommendation',
        'Request Letter': 'Request Letter',
        'Cancel': 'Cancel',
        'Submit': 'Submit',
        'Submit Request': 'Submit Request',
        'Back': 'Back',
        'Download PDF': 'Download PDF',
        'Open in New Tab': 'Open in New Tab',
        'Upload PDF Document': 'Upload PDF Document',
        'Choose PDF File': 'Choose PDF File',
        'Approve & Upload': 'Approve & Upload',
        'Reject Request': 'Reject Request',
        'Issue & Upload': 'Issue & Upload',
        'Send & Issue': 'Send & Issue',
        'Update Decree': 'Update Decree',
        'Apply Leave': 'Apply Leave',

        // Titles and Subtitles
        'official_decree_sk': 'Official Decree (SK)',
        'review_pending_statement':
            'Review pending statement letter requests, approve by issuing PDFs, or reject requests.',
        'request_active_employment':
            'Request active employment, salary statements, active student, or SKPI certificates.',
        'review_pending_recommendation':
            'Issue and upload signed official recommendation letters directly for employees.',
        'official_recommendation_umsu':
            'Official recommendation letters of Universitas Muhammadiyah Sumatera Utara.',
        'issue_and_manage_decrees':
            'Issue and manage official decrees (SK / Decrees) for targeted employees.',
        'official_decrees_issued':
            'Official decrees (SK / Decrees) issued for you.',
        'manage_circular_letters':
            'Manage and distribute official circular letters to departments online.',
        'official_circular_letters_umsu':
            'Official circular letters of Universitas Muhammadiyah Sumatera Utara.',
        'Apply for and track your time-off requests':
            'Apply for and track your time-off requests',
        'Manage employee leave and time-off requests':
            'Manage employee leave and time-off requests',

        // Dashboard
        'Monthly Attendance': 'Monthly Attendance',
        'Overall Attendance': 'Overall Attendance',

        // Labels
        'Applicant': 'Applicant',
        'position': 'Position',
        'department': 'Department',
        'not_set': 'Not set',
        'unknown': 'Unknown',
        'active': 'Active',
        'non_active': 'Non-Active',
        'permanent': 'Permanent',
        'contract': 'Contract',
        'honorarium': 'Honorarium',
        'internship': 'Internship',
        'Recipient': 'Recipient',
        'Recipient Employee': 'Recipient Employee',
        'Recipient Employee / User': 'Recipient Employee / User',
        'Letter Type': 'Letter Type',
        'Reason': 'Reason / Purpose',
        'Reason / Purpose of Request': 'Reason / Purpose of Request',
        'Reason / Purpose / Notes': 'Reason / Purpose / Notes',
        'Purpose / Notes': 'Purpose / Notes',
        'Status': 'Status',
        'Result / Reference': 'Result / Reference',
        'Actions': 'Actions',
        'Search': 'Search',
        'Pending': 'PENDING',
        'Approved': 'APPROVED',
        'Rejected': 'REJECTED',
        'Search letter number or title...': 'Search letter number or title...',
        'Search by number, reason, or applicant...':
            'Search by number, reason, or applicant...',
        'Search by number, notes, or employee...':
            'Search by number, notes, or employee...',
        'All Status': 'All Status',
        'No data found.': 'No data found.',
        'No statement letters found.': 'No statement letters found.',
        'No recommendation letters found.': 'No recommendation letters found.',
        'No SK / Decrees found.': 'No SK / Decrees found.',
        'No circular letters found.': 'No circular letters found.',
        'Letter Number': 'Letter Number',
        'SK Number': 'SK Number',
        'Letter Date': 'Letter Date',
        'Decree Date': 'Decree Date',
        'Decree Title': 'Decree Title',
        'Decree (SK) Title': 'Decree (SK) Title',
        'Decree (SK) Number': 'Decree (SK) Number',
        'Signed By': 'Signed By',
        'Signature Type': 'Signature Type',
        'Wet Signature': 'Wet Signature',
        'Digital Signature (TTE)': 'Digital Signature (TTE)',
        'Digital TTE': 'Digital (TTE)',
        'Digital (TTE)': 'Digital (TTE)',
        'Targeted Employees': 'Targeted Employees',
        'Targets': 'Targets',
        'Document Information': 'Document Information',
        'Document Details': 'Document Details',
        'Integrated PDF Canvas': 'Integrated PDF Canvas',
        'Recommendation Issued': 'Recommendation Issued',
        'Letter Information': 'Letter Information',
        'Request Details': 'Request Details',
        'Issued Date': 'Issued Date',
        'Date': 'Date',
        'Title of Decree': 'Title of Decree',
        'Title of Circular Letter': 'Title of Circular Letter',
        'Title of Letter': 'Title of Letter',
        'Summary Description': 'Summary Description',
        'Recipients': 'Recipients',
        'Shift Management': 'Shift Management',
        'Shift Schedules': 'Shift Schedules',
        'Kelola data master shift kerja.': 'Manage work shift master data.',
        'Atur jadwal shift dan tukar shift.':
            'Manage shift schedules and swap requests.',
        'Kelola pengajuan tukar shift antar pegawai.':
            'Manage shift swap requests between employees.',
        'Hanya akun yang terhubung ke data pegawai yang dapat mengajukan tukar.':
            'Only accounts linked to employee data can request a swap.',
        'Ajukan Tukar Shift': 'Request Shift Swap',
        'Atur Shift': 'Manage Shifts',
        'Belum ada pengajuan tukar shift.': 'No shift swap requests yet.',
        'Holiday Management': 'Holiday Management',
        'Manage list of holidays.': 'Manage list of holidays.',
        'Add Holiday': 'Add Holiday',
        'Search holiday...': 'Search holiday...',
        'Holiday Name': 'Holiday Name',
        'No holidays found.': 'No holidays found.',
        'Edit Holiday': 'Edit Holiday',
        'Delete Holiday': 'Delete Holiday',
        'Change the details of this holiday.':
            'Change the details of this holiday.',
        'Add a new holiday to the system.': 'Add a new holiday to the system.',
        'Enter holiday name': 'Enter holiday name',
        'Active': 'Active',
        'Inactive': 'Inactive',
        'Kelola hierarki menu navigasi sistem.':
            'Manage system navigation menu hierarchy.',
        'Issue and assign official letters of duties to specific employees.':
            'Issue and assign official letters of duties to specific employees.',
        'Official assignment letters of duties issued to you.':
            'Official assignment letters of duties issued to you.',
        'Select all': 'Select All',
        'Save': 'Save',
        'Update': 'Update',
        'Confirm': 'Confirm',
        'Settings': 'Settings',
        'Log out': 'Log out',
        'Language / Bahasa': 'Language / Bahasa',
        'Total Days': 'Total Days',
        'Attachment': 'Attachment',
        'Leave Balance Information': 'Leave Balance Information',
        'Total Quota': 'Total Quota',
        'Used / Pending': 'Used / Pending',
        'Remaining': 'Remaining',
        'Days': 'Days',
        'Start Date': 'Start Date',
        'End Date': 'End Date',
        'to': 'to',
        'Required for some leaves': 'Required for some leaves',
        'Choose File': 'Choose File',
        'PDF, JPG, PNG format, max 2MB': 'PDF, JPG, PNG format, max 2MB',
        '*The remaining balance above applies to the current year. Ensure you do not apply for more than your remaining days.':
            '*The remaining balance above applies to the current year. Ensure you do not apply for more than your remaining days.',
        'Employee': 'Employee',
        'Leave Details': 'Leave Details',
        'Leave Request Details': 'Leave Request Details',

        // Modals
        'Create Time Off Request': 'Create Time Off Request',
        'Submit a time off request for an employee.': 'Submit a time off request for an employee.',
        'Employee Email': 'Employee Email',
        'Select Employee': 'Select Employee',
        'Leave Type': 'Leave Type',
        'Casual Leave': 'Casual Leave',
        'Sick Leave': 'Sick Leave',
        'Annual Leave': 'Annual Leave',
        'Unpaid Leave': 'Unpaid Leave',
        'Reason (Optional)': 'Reason (Optional)',
        'Create & Approve': 'Create & Approve',
        'Create Request': 'Create Request',
        'Provide reason for time off...': 'Provide reason for time off...',
        'Approve Time Off Request': 'Approve Time Off Request',
        'Reject Time Off Request': 'Reject Time Off Request',
        'Time Off Request Details': 'Time Off Request Details',
        'Delete Statement Letter': 'Delete Statement Letter',
        'Delete Recommendation Letter': 'Delete Recommendation Letter',
        'Delete SK / Decree': 'Delete SK / Decree',
        'Delete Circular Letter': 'Delete Circular Letter',
        'confirm_delete_statement':
            'Are you sure you want to delete this requested letter? Any uploaded PDF file will also be permanently deleted.',
        'confirm_delete_recommendation':
            'Are you sure you want to delete this issued recommendation letter? The uploaded PDF file will also be permanently deleted.',
        'confirm_delete_sk':
            'Are you sure you want to delete this SK / Decree? The uploaded PDF file will also be permanently deleted from the server.',
        'confirm_delete_circular':
            'Are you sure you want to delete this circular letter? The uploaded PDF file will also be permanently deleted from the server.',
        'Approve Letter Request': 'Approve Letter Request',
        'Reject Letter Request': 'Reject Letter Request',
        'Rejection Reason': 'Rejection Reason',
        'Write a brief explanation for rejecting this request...':
            'Write a brief explanation for rejecting this request...',
        'Signer Authority': 'Signer Authority',
        'Select Signer': 'Select Signer',
        'Select Recipient': 'Select Recipient',
        'Daftar Partisipan': 'Participant List',
        'Manage and view attendance records.':
            'Manage and view attendance records.',
        'Rekapitulasi Absensi': 'Attendance Recapitulation',
        'Laporan ringkasan data absensi karyawan':
            'Summary report of employee attendance data.',
        'Manajemen hak akses role terhadap menu dan aksi sistem.':
            'Manage role access rights to menus and system actions.',
        'Manajemen hak akses user terhadap menu dan aksi sistem.':
            'Manage user access rights to menus and system actions.',
        'Menu Management': 'Menu Management',
        'Permission Management': 'Permission Management',
        'Kelola permission sistem.': 'Manage system permissions.',
        'Role Management': 'Role Management',
        'Kelola role akses sistem.': 'Manage system access roles.',
        'User Management': 'User Management',
        'Kelola data pengguna dan akses peran mereka.':
            'Manage user data and their role access.',
        'Fill out the form below to assign and distribute the official task letter.':
            'Fill out the form below to assign and distribute the official task letter.',
        'Correspondence - Assignment Letters':
            'Correspondence - Assignment Letters',
        'Fill out the form below to distribute the official circular letter.':
            'Fill out the form below to distribute the official circular letter.',
        'Correspondence - Circular Letters':
            'Correspondence - Circular Letters',
        'Fill out the form below to issue and distribute the official decree (Surat Keputusan).':
            'Fill out the form below to issue and distribute the official decree (Surat Keputusan).',
        'Event Management': 'Event Management',
        'Kelola jadwal event, rapat, dan agenda kantor secara online maupun offline.':
            'Manage event schedules, meetings, and office agendas online or offline.',
        'Employee Management': 'Employee Management',
        'Kelola data pegawai dan informasi kepegawaian.':
            'Manage employee data and HR information.',
        'Department Management': 'Department Management',
        'Kelola struktur organisasi dan departemen.':
            'Manage organizational structures and departments.',
        'Location Management': 'Location Management',
        'Kelola data lokasi.': 'Manage location data.',
        'Position Management': 'Position Management',
        'Kelola jabatan/jenjang pegawai.': 'Manage employee positions/levels.',
        'Create New Circular Letter': 'Create New Circular Letter',
        'Edit Circular Letter': 'Edit Circular Letter',
        'Create New Assignment Letter': 'Create New Assignment Letter',
        'Edit Assignment Letter': 'Edit Assignment Letter',
        'Employees by Work Unit': 'Employees by Work Unit',
        'Overview': 'Overview',
        "Welcome back! Here's what's happening today.":
            "Welcome back! Here's what's happening today.",
        'Employees Total': 'Employees Total',
        'Registered in the system': 'Registered in the system',
        'Active Events': 'Active Events',
        'Events that are currently running':
            'Events that are currently running',
        'Attendance (Today)': 'Attendance (Today)',
        'Employees present today': 'Employees present today',
        'Total Department': 'Total Department',
        'Registered work unit': 'Registered work unit',
        'Employee Attendance':
            'Employee Attendance',
        'There is no absence data.':
            'There is no absence data.',
        'There is no employee data yet.': 'There is no employee data yet.',
        'Complete Data': 'Complete Data',
        'Incomplete Data': 'Incomplete Data',
        'Work units have been filled': 'Work units have been filled',
        'Work units not yet filled': 'Work units not yet filled',
        'Report summary of employee attendance data':
            'Report summary of employee attendance data',
        'Export Excel': 'Export Excel',
        'Attendance Recapitulation': 'Attendance Recapitulation',
        'All Type': 'All Type',
        'Alfa': 'Alfa',
        'Late': 'Late',

        // Dynamic Performance Rules
        'Sangat Baik': 'Excellent',
        'Cukup': 'Average',
        'Perlu Evaluasi': 'Needs Evaluation',
        'SP 1': 'Warning Letter 1',
        'SP 2': 'Warning Letter 2',
        'SP 3': 'Warning Letter 3',
        'Terlambat': 'Late',
        'Tepat Waktu': 'On Time',
        'Alpa': 'Absent',

        'Hijau': 'Green',
        'Oranye': 'Orange',
        'Merah': 'Red',
        'Biru': 'Blue',
        'Kuning': 'Yellow',
        'Abu-abu': 'Slate',
        'Ungu': 'Purple',

        'Reference Settings': 'Reference Settings',
        'Kelola konfigurasi sistem dan referensi.':
            'Manage system configurations and referencies.',
        'Pengaturan Performa (Rentang Pelanggaran)':
            'Performance Settings (Violation Range)',
        'Konfigurasi rentang akumulasi hari terlambat dan alpa untuk menentukan label performa secara dinamis.':
            'Configure the accumulation range of late and absent days to determine performance labels dynamically.',
        'Min': 'Min',
        'Max': 'Max',
        'Label Teks': 'Text Label',
        'Warna Label': 'Label Color',
        'Tambah Rentang Baru': 'Add New Range',
        'Simpan Semua Pengaturan': 'Save All Settings',
        'Tak Terhingga': 'Infinity',

        // Push Notifications
        'Push Notifications': 'Push Notifications',
        'Push notification berhasil dikirim.': 'Push notification sent successfully.',
        'Gagal mengirim push notification. Pastikan input valid.': 'Failed to send push notification. Please ensure valid input.',
        'Kirim dan kelola riwayat notifikasi langsung ke perangkat pegawai.': 'Send and manage notification history directly to employee devices.',
        'Kirim Notifikasi': 'Send Notification',
        'Waktu': 'Time',
        'Judul': 'Title',
        'Isi Pesan': 'Message',
        'Penerima': 'Recipient',
        'Pengirim': 'Sender',
        'Pegawai': 'Employee',
        'Belum ada riwayat notifikasi.': 'No notification history yet.',
        'Kirim Notifikasi Baru': 'Send New Notification',
        'Pilih pegawai secara spesifik untuk menerima notifikasi ini.': 'Select specific employees to receive this notification.',
        'Batal': 'Cancel',
        'Mengirim...': 'Sending...',
        'Judul Notifikasi': 'Notification Title',
        'Contoh: Pembaruan Biodata': 'Example: Profile Update',
        'Pesan': 'Message',
        'Silakan lengkapi biodata Anda di menu profil...': 'Please complete your profile in the profile menu...',
        'Kirim Ke (Pegawai)': 'Send To (Employee)',
        'Pilih satu atau lebih pegawai': 'Select one or more employees',

        //Settings
        'Profile information': 'Profile information',
        'Update your name and email address': 'Update your name and email address',
        'Update your profile information.': 'Update your profile information.',
        'Email Address': 'Email Address',
        'Name': 'Name',
        'Verification link has been sent to your email address': 'Verification link has been sent to your email address.',
        'Profile settings': 'Profile settings',
        'Full name': 'Full name',
        'Your email address is unverified.': 'Your email address is unverified.',
        'Click here to resend the verification email.': 'Click here to resend the verification email.',
        'Update your profile information': 'Update your profile information',
        'Warning': 'Warning',
        'Please proceed with caution, this cannot be undone.': 'Please proceed with caution, this cannot be undone.',
        'Are you sure you want to delete your account?': 'Are you sure you want to delete your account?',
        'Once your account is deleted, all of its resources and data will also be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.': 'Once your account is deleted, all of its resources and data will also be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.',
        'Password': 'Password',
        'Profile photo': 'Profile photo',
        'Update your profile picture': 'Update your profile picture',
        'Change Photo': 'Change Photo',
        'Save Photo': 'Save Photo',
        
        // Lecturer Courses
        'Mata Kuliah Anda': 'Your Courses',
        'Kelola dan pantau seluruh mata kuliah yang Anda ampu pada periode akademik saat ini.': 'Manage and monitor all courses you are teaching in the current academic period.',
        'Total Kelas': 'Total Classes',
        'Sesuai Jadwal': 'As Scheduled',
        'Lihat Partisipan': 'View Participants',
        'Belum Ada Mata Kuliah': 'No Courses Yet',
        'Anda belum terdaftar sebagai pengajar untuk mata kuliah apapun pada periode ini.': 'You are not registered as a lecturer for any course in this period.',
        'Sebelumnya': 'Previous',
        'Selanjutnya': 'Next',
        'Halaman': 'Page',
        'dari': 'of',
        'Academic Semester': 'Academic Semester',
        'Partisipan Kelas': 'Class Participants',
        'Daftar Mahasiswa': 'Student List',
        'Total': 'Total',
        'mahasiswa terdaftar pada mata kuliah ini.': 'students registered in this course.',
        'Gagal memuat data partisipan.': 'Failed to load participant data.',
        'Terjadi kesalahan saat memuat data partisipan.': 'An error occurred while loading participant data.',
        'No': 'No',
        'NPM': 'NPM',
        'Nama Mahasiswa': 'Student Name',
        'Jenis Kelamin': 'Gender',
        'Program Studi': 'Study Program',
        'Kelas': 'Class',
        'Laki-laki': 'Male',
        'Perempuan': 'Female',
        'Belum ada mahasiswa yang terdaftar': 'No students registered yet',
        'Hal': 'Page',
        'Academic': 'Academic',
        'Courses': 'Courses',
        'Teaching Schedules': 'Teaching Schedules',
        'Jadwal Mengajar': 'Teaching Schedule',
        'Jadwal Mengajar Anda': 'Your Teaching Schedules',
        'Pantau jadwal mengajar Anda untuk periode akademik saat ini.': 'Monitor your teaching schedules for the current academic period.',
        'Total Jadwal': 'Total Schedules',
        'Belum ada jadwal': 'No schedule yet',
        'Belum Ada Jadwal': 'No Schedule Yet',
        'Anda belum memiliki jadwal mengajar untuk periode ini.': 'You do not have any teaching schedules for this period.',

        // Attendance Claims
        'Riwayat Claim Absensi': 'Attendance Claim History',
        'Daftar riwayat klaim absensi yang dilakukan oleh admin atau manajer.': 'List of attendance claim history made by admins or managers.',
        'Data Riwayat Claim': 'Claim History Data',
        'Waktu Klaim': 'Claim Time',
        'Pegawai (Email)': 'Employee (Email)',
        'Diklaim Oleh': 'Claimed By',
        'Alasan': 'Reason',
        'Tidak ada riwayat klaim.': 'No claim history.',
        'Failed to load data for claim': 'Failed to load data for claim',
        'Attendances claim generation has been started in the background.': 'Attendances claim generation has been started in the background.',
        'Failed to process attendance claims.': 'Failed to process attendance claims.',
        'Claim': 'Claim',
        'Attendances Claim': 'Attendances Claim',
        'Submit attendance claims for employees.': 'Submit attendance claims for employees.',
        'Select Employees': 'Select Employees',
        'Date Range': 'Date Range',
        'Include Check-In': 'Include Check-In',
        'Check-In Time': 'Check-In Time',
        'Include Check-Out': 'Include Check-Out',
        'Check-Out Time': 'Check-Out Time',
        'Location': 'Location',
        'Select Location': 'Select Location',
        'Catatan / Alasan Claim': 'Note / Claim Reason',
        'Masukkan alasan melakukan claim ini...': 'Enter reason for this claim...',
        'Saving...': 'Saving...',
        'Submit Claim': 'Submit Claim',
        'Konfirmasi Data': 'Confirm Data',
        'Pastikan data attendance claim yang Anda isi sudah benar. Anda yakin ingin melanjutkan?': 'Make sure the attendance claim data you filled in is correct. Are you sure you want to proceed?',
        'Ya, Simpan': 'Yes, Save',
        'Cari...': 'Search...',
        'Cari': 'Search',
    },
};
